### ISSUE TITLE
uses-sdk element cannot have a "tools:node" attribute

### ISSUE THREAD

**Issue by dcampogiani** [gorbin/ASNE#46]
I've updated Android Studio to version 0.9, and gradle build tools to version 0.14, now when i try to build my application (which is using ASNE) I got this error:

Error:Execution failed for task ':app:processDebugManifest'. Manifest merger failed : uses-sdk element cannot have a "tools:node" attribute

I've searched in my code, and I'm not using tools:node="replace" anywhere, but ASNE is using in manifest (both in core and "modules").

Any idea how I can solve this problem?

**Comment by vishnudbimcs** [comment]
Still have the Problem. Please Help

**Comment by matantsu** [comment]
updated to 0.3.3
now the problem is:
```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/root/Android/Sdk/build-tools/21.1.2/dx --dex --no-optimize --output /home/matan/AndroidStudioProjects/Stars/app/build/intermediates/dex/debug --input-list=/home/matan/AndroidStudioProjects/Stars/app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
  		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
  		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
  		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by 4emodan** [comment]
@matantsu your problem is not related. You have over 65r methods in your project. Check https://developer.android.com/tools/building/multidex.html

**Comment by mohamed-habib** [comment]
I still have this problem,

Android Studio 1.2.2

**Comment by mohamed-habib** [comment]
I Found a solution to this problem,

In AndroidManifest file
-add this line to mainfest tag:
    xmlns:tools="http://schemas.android.com/tools"

-add this tag:
    <uses-sdk
        tools:node="merge"
    android:minSdkVersion=MIN_SDK
    android:targetSdkVersion=TARGET_SDK />

**Comment by Dandewine** [comment]
@mohamed-habib, can you post some code?

**Comment by mohamed-habib** [comment]
I don't understand what code exactly do you want?
my last comment was code to be written in the manifest file.

**Comment by falkolab** [comment]
`<uses-sdk
        tools:node="merge"
        android:minSdkVersion="MIN_SDK"
        android:targetSdkVersion="TARGET_SDK" />`
