### ISSUE TITLE
Using ASNE library from activity, not from fragment

### ISSUE THREAD

**Issue by Aracem** [gorbin/ASNE#68]
I integratin ASNE library in a base activity that let use login in all the screens of the application.

The problem is that SocialNetwork inicialization needs a Fragment to be instanciate.

I can instanciate a SocialNetwork with the SocialNetworkManager fragment but if I make this:

public final void configureSocialLibrary() {
        mSocialNetworkManager = new SocialNetworkManager();
        mSocialNetworkManager.addSocialNetwork(getTwitterSocialNetwork());
        mSocialNetworkManager.addSocialNetwork(getFacebookSocialNetwork());
        mSocialNetworkManager.addSocialNetwork(getGoogleSocialNetwork());
        getSupportFragmentManager().beginTransaction().add(mSocialNetworkManager, SOCIAL_TAG).commit();
        mSocialNetworkManager.setOnInitializationCompleteListener(this);
    }

It crash in the SocialNetwork class trying to get the SharedPreferences.

In the tutorial the solution is pass the Fragment that controls the buttons and that stuff instead of pass the SocialNetworkManager but this is not possible because I dont need Fragments to make the login -- remember I want to make login in every part of the app.

I try, of course, of add the social networks before commit the social manager but doesn't works for evident reasons.

Are there some solution for this or I need to make a fork with a builder with Fragment and Activity to fix the problem?

**Comment by Aracem** [comment]
I revised the code of Google Plus, Twitter and Facebook social networks and the Fragment is not used for nothing more than fragment.getActivity().

In the documentation of the SocialNetwork class says:
"@param fragment ant not activity or context, as we will need to call startActivityForResult,
                we will want to receice on onActivityResult in out SocialNetworkManager
                fragment"

But it has no sense because the Activity can pass the onActivityResult with the simple code of:
Fragment fragment = getSupportFragmentManager().findFragmentByTag(SOCIAL_TAG);
        if (fragment != null) {
            fragment.onActivityResult(requestCode, resultCode, data);
        }

ĺike the original Android Social Network library.
If I have to use ASNE inside a Fragments destroys the amaaaazing modularization of the library :(

Anyway, I going to try this .... shitty ... ugly ... shameful patch: extends Fragment and override "getActivity" to return the activity without make a commit, only to test if its possible to use without a real fragment

**Comment by frostymarvelous** [comment]
I was having issues with this issue as well. I wrote my own fix like this

    protected SocialNetwork(Fragment fragment, Context context) {
            mSocialNetworkManager = fragment;
            mSharedPreferences = context.getSharedPreferences(SHARED_PREFERENCES_NAME, Context.MODE_PRIVATE);
    }

So I used it like so

    FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(mSocialNetworkManager, ctx, fbScope);

    GooglePlusSocialNetwork gpNetwork = new GooglePlusSocialNetwork(mSocialNetworkManager, ctx);

I simply pass the socialNetworkManager fragment from my activity as the fragment and the activity as context. Obviously, the relevant SocialNetworkClasses (I am only using facebook and google) were modified.

**Comment by tylerjroach** [comment]
@frostymarvelous Really nice solution!

**Comment by frostymarvelous** [comment]
Thanks  @tylerjroach

**Comment by Aracem** [comment]
@frostymarvelous can you make a pull request with the solution? 

Thank you very much

**Comment by frostymarvelous** [comment]
ASAP. My computer died on me this morning.

**Comment by frostymarvelous** [comment]
Done. Can someone please review it for me, I couldn't make a build to test it.

**Comment by Aracem** [comment]
Thanks @frostymarvelous We have to wait @gorbin to accept it

**Comment by pierrexn** [comment]
I try to use your changes to use ASNE into an Activity, but it doens't work, fragment.getActivity() is null

mSocialNetworkManager = new SocialNetworkManager();
ArrayList<String> fbScope = new ArrayList<String>();
fbScope.addAll(Arrays.asList("public_profile, email, user_friends"));
FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(mSocialNetworkManager, this, fbScope);
mSocialNetworkManager.addSocialNetwork(fbNetwork);

**Comment by frostymarvelous** [comment]
@pierrexn  did you change SocialNetwork like below as well??

    protected SocialNetwork(Fragment socialMediaManager, Context context) {
        //we keep the fragment in case it is needed in future. it also minimises the changes required.
        mSocialNetworkManager = socialMediaManager;
        mSharedPreferences = context.getSharedPreferences(SHARED_PREFERENCES_NAME, Context.MODE_PRIVATE);
    }

**Comment by pierrexn** [comment]
yes, it works if i replace in FacebookSocialNetwork, fragment.getActivity() by context

**Comment by frostymarvelous** [comment]
O man! I missed it 

    String applicationID = Utility.getMetadataApplicationId(fragment.getActivity());

should be 

String applicationID = Utility.getMetadataApplicationId(context);

**Comment by frostymarvelous** [comment]
@pierrexn fixed with this https://github.com/frostymarvelous/ASNE/commit/9c32049751ecfcddc681f2a9a64c7df411f693e7

**Comment by amouly** [comment]
@Aracem what about this? I need to fix this immediately, how is possible that this fix is not on the build yet?

**Comment by frostymarvelous** [comment]
I think he no longer maintains this. We might need another fork.

**Comment by Aracem** [comment]
Yes, as @gorbin says in the Readme:

```Sorry, but I freeze work on project for some time(I hope not long, nearly month) - too busy. I saw all Issues and will resolve them as soon as I can.

I checked project - current maven libs mostly works fine. For now I need help with Issues and open for pull requests - will check them and merge on weekends.```

I have more or less ready a PR with Fabric integration that could be good for others. Perhaps is time to create a Fork to continuing the work

**Comment by frostymarvelous** [comment]
Let's go ahead and create the Fork. This is a critical library. When Login fails, users run!

**Comment by amouly** [comment]
I just need to instantiate the Manager from Activity, not from Fragment.

**Comment by gorbin** [comment]
Hello, guys I'm really sorry, I'm too busy now and cant maintains ASNE, but I check and update it on vacation as soon as posible.
But if you want to pull new features or updated possibilities I check it on my free time. Or I can add somebody to repo owners to update it more quikcly.

I will maintains this repo but only when I'm really can, sorry for this

**Comment by frostymarvelous** [comment]
@gorbin Make me and owner on the lib.

It needs some work and I am willing to maintain it.

**Comment by gorbin** [comment]
@frostymarvelous add you as collaborator, thruly there are a lot of work to do.
I am planning update gradle, all dependecies and solve issues.
right now want to update master branch, then work in dev to restore functionality, only after test merge it to master and build release for libs, then update it in central - to restore functionality
You can contact with me via email to discuss plans.

**Comment by frostymarvelous** [comment]
Great. Sure thing.
