### ISSUE TITLE
Google requestForAccessToken fails if UserRecoverableAuthException is thrown

### ISSUE THREAD

**Issue by frostymarvelous** [gorbin/ASNE#77]
Fails to retrieve oauth token and error handler is not called when an exception occurs.
The current method fails to handle UserRecoverableAuthException and simply returns the exception message which the  onPostExecute method interprets as a token.

**Comment by arthur-feral** [comment]
Hi,
GooglePlusSocialNetwork login works (i checked isConnected() ), but requestCurrentPerson() doesn't seems to work properly and requestAccessToken() give me a accessToken.token == Unknow
