### ISSUE TITLE
How to check if user is already logged in through any Social Login and move to the next activity

### ISSUE THREAD

**Issue by pnpninja** [gorbin/ASNE#99]
I got the ASNETutorial application. However, I want to check if the user was already logged in . If so, I want to move to another activity (check if user was already logged in in MainActivity). How do I do that?

**Comment by Lawliet666** [comment]
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_login, container, false);
        mSocialNetworkManager = new SocialNetworkManager();

        ArrayList<String> fbScope = new ArrayList<String>();
        fbScope.addAll(Arrays.asList("public_profile, email, user_friends"));

        FacebookSocialNetwork fbNetwork = new FacebookSocialNetwork(this, fbScope);
        mSocialNetworkManager.addSocialNetwork(fbNetwork);

       getFragmentManager()
                .beginTransaction()
                .add(mSocialNetworkManager,SOCIAL_NETWORK_TAG)
                .commit();

        mSocialNetworkManager.setOnInitializationCompleteListener(this);
        
        return v;
    }

@Override
    public void onSocialNetworkManagerInitialized() {
        Log.d("onSocialNetworkManagerInitialized");
        for (SocialNetwork socialNetwork : SocialNetworks.getInstance().getInitializedSocialNetworks()) {
                socialNetwork.setOnLoginCompleteListener(this);
                initSocialNetwork(socialNetwork);
        }
    }

    private void initSocialNetwork(SocialNetwork socialNetwork) {
        if (socialNetwork.isConnected()){
            // start next activity
        }
    }
